#require: rubocop-rspec

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Documentation:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: false
  
# Include this in your local .rubocop.yml file if you are using Rails
# Rails:
#   Enabled: true
